name: User Story
description: Create a User Story
title: 'As a ____, I want ____, so that I can ____'
labels: []
body:
  - type: input
    id: contact
    attributes:
      label: Definition of Done
      description: What needs to be done for this user story to be considered done?
      placeholder: |
        - [ ] Does the horse donkey?
        - [ ] Flux capacitor charged
        - [ ] Can reach 88 MPH
    validations:
      required: false
