name: Generate Documentation
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest

    name: Publish latest API documentation

    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Setup dependencies
        run: npm install apidoc -g
      - name: Create documentation
        run: apidoc -i backend -o _site -c backend/apidoc.json
      - name: Upload GitHub Pages artifact
        if: ${{ github.ref == 'ref/heads/main' }}
        uses: actions/upload-pages-artifact@v1.0.8
      - name: Deploy GitHub Pages
        if: ${{ github.ref == 'ref/heads/main' }}
        uses: actions/deploy-pages@v1
