name: Generate Documentation
on:
  push:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish latest release
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Setup dependencies
        run: npm install apidoc -g
      - name: Create documentation
        run: apidoc -i backend -o _site -c backend/apidoc.json
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.8
